from tkinter import * 
import Main

class BotGUI:

    def __init__(self,master):
        guifuncs = Main.GUI_Functions(master)
        master.title('Calculator') 
        master.geometry("245x160") 
        equation = StringVar() 
        expression_field = Entry(master,textvariable=equation,bg="light gray",width=40)
        expression_field.grid(row=0,column=0,columnspan=4,padx=1,pady=5) 
        equation.set('enter your expression') 

        B=Button(master,text=' 9 ',activebackground="grey",command=lambda : guifuncs.press(9), height=1, width=7)
        B.grid(row=8, column=2)
        B=Button(master,text=' 8 ',activebackground="grey",command=lambda : guifuncs.press(8), height=1, width=7)
        B.grid(row=8, column=1) 
        B=Button(master,text=' 7 ',activebackground="grey",command=lambda : guifuncs.press(7), height=1, width=7)
        B.grid(row=8, column=0) 
        B=Button(master,text=' 6 ',activebackground="grey",command=lambda : guifuncs.press(6), height=1, width=7)
        B.grid(row=7, column=2) 
        B=Button(master,text=' 5 ',activebackground="grey",command=lambda : guifuncs.press(5), height=1, width=7)
        B.grid(row=7, column=1)
        B=Button(master,text=' 4 ',activebackground="grey",command=lambda : guifuncs.press(4), height=1, width=7)
        B.grid(row=7, column=0)  
        B=Button(master,text=' 3 ',activebackground="grey",command=lambda : guifuncs.press(3), height=1, width=7)
        B.grid(row=6, column=2)
        B=Button(master,text=' 2 ',activebackground="grey",command=lambda : guifuncs.press(2), height=1, width=7)
        B.grid(row=6, column=1)
        B=Button(master,text=' 1 ',activebackground="grey",command=lambda : guifuncs.press(1), height=1, width=7)
        B.grid(row=6, column=0) 
        B=Button(master,text=" √ ",activebackground="grey",command=lambda : guifuncs.press(" √ "), height=1, width=7)
        B.grid(row=5, column=0)
        B=Button(master,text=" x²",activebackground="grey",command=lambda : guifuncs.press(" x²"), height=1, width=7)
        B.grid(row=5, column=1)
        B=Button(master,text="1/x",activebackground="grey",command=lambda : guifuncs.press("1/x"), height=1, width=7)
        B.grid(row=5, column=2)
        B=Button(master,text=' + ',activebackground="grey",command=lambda : guifuncs.press(' + '), height=1, width=7)
        B.grid(row=5, column=3)
        B=Button(master,text=' - ',activebackground="grey",command=lambda : guifuncs.press(' - '), height=1, width=7)
        B.grid(row=6, column=3)
        B=Button(master,text=' * ',activebackground="grey",command=lambda : guifuncs.press(' * '), height=1, width=7)
        B.grid(row=7, column=3)
        B=Button(master,text=' / ',activebackground="grey",command=lambda : guifuncs.press(' / '), height=1, width=7)
        B.grid(row=8, column=3) 
        B=Button(master,text="  =  ",activebackground="grey",command=guifuncs.equalpress, height=1, width=34)
        B.place(x=0,y=135)
        clear = Button(master, text='Clear', fg='black', bg='red',activebackground="grey",command=guifuncs. clear, height=1, width=7)
        clear.grid(row=5, column=0)
