from tkinter import *
import GUI 

if __name__ == "__main__":
    root = Tk()
    GUI_Frame = GUI.BotGUI(root)
    B=Button(root,text=' 9 ',activebackground="grey",command=lambda : GUI_Frame.press(9), height=1, width=7)
    B.grid(row=8, column=2)
    B=Button(root,text=' 8 ',activebackground="grey",command=lambda : GUI_Frame.press(8), height=1, width=7)
    B.grid(row=8, column=1) 
    B=Button(root,text=' 7 ',activebackground="grey",command=lambda : GUI_Frame.press(7), height=1, width=7)
    B.grid(row=8, column=0) 
    B=Button(root,text=' 6 ',activebackground="grey",command=lambda : GUI_Frame.press(6), height=1, width=7)
    B.grid(row=7, column=2) 
    B=Button(root,text=' 5 ',activebackground="grey",command=lambda : GUI_Frame.press(5), height=1, width=7)
    B.grid(row=7, column=1)
    B=Button(root,text=' 4 ',activebackground="grey",command=lambda : GUI_Frame.press(4), height=1, width=7)
    B.grid(row=7, column=0)  
    B=Button(root,text=' 3 ',activebackground="grey",command=lambda : GUI_Frame.press(3), height=1, width=7)
    B.grid(row=6, column=2)
    B=Button(root,text=' 2 ',activebackground="grey",command=lambda : GUI_Frame.press(2), height=1, width=7)
    B.grid(row=6, column=1)
    B=Button(root,text=' 1 ',activebackground="grey",command=lambda : GUI_Frame.press(1), height=1, width=7)
    B.grid(row=6, column=0) 
    B=Button(root,text=" √ ",activebackground="grey",command = GUI_Frame.square, height=1, width=7)
    B.grid(row=5, column=0)
    B=Button(root,text=" x²",activebackground="grey",command = GUI_Frame.exponent, height=1, width=7)
    B.grid(row=5, column=1)
    B=Button(root,text="1/x",activebackground="grey",command = GUI_Frame.one_div_x, height=1, width=7)
    B.grid(row=5, column=2)
    B=Button(root,text=' + ',activebackground="grey",command=lambda : GUI_Frame.press(' + '), height=1, width=7)
    B.grid(row=5, column=3)
    B=Button(root,text=' - ',activebackground="grey",command=lambda : GUI_Frame.press(' - '), height=1, width=7)
    B.grid(row=6, column=3)
    B=Button(root,text=' * ',activebackground="grey",command=lambda : GUI_Frame.press(' * '), height=1, width=7)
    B.grid(row=7, column=3)
    B=Button(root,text=' / ',activebackground="grey",command=lambda : GUI_Frame.press(' / '), height=1, width=7)
    B.grid(row=8, column=3) 
    B=Button(root,text="  =  ", bg='lightgreen', activebackground="grey",command = GUI_Frame.equalpress, height=1, width=24)
    B.place(x=64,y=133)
    clear = Button(root, text='Clear', fg='black', bg='pink',activebackground="grey",command = GUI_Frame.clear, height=1, width=7)
    clear.grid(row=9, column=0)
    # guifunc = GUI.GUI_Functions(root)
    root.mainloop()
    